// my-project/frontend-react/src/App.jsx
import { useState, useEffect } from 'react'

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000'

export default function App() {
  const [items,      setItems]      = useState([])
  const [loading,    setLoading]    = useState(true)
  const [error,      setError]      = useState(null)
  const [dbMsg,      setDbMsg]      = useState('확인 중...')
  const [dbOk,       setDbOk]       = useState(null)
  const [newName,    setNewName]    = useState('')
  const [newContent, setNewContent] = useState('')

  const checkDB = async () => {
    try {
      const res  = await fetch(`${API}/db-check`)
      const data = await res.json()
      setDbMsg(`연결됨 (총 ${data.items_count}건)`)
      setDbOk(true)
    } catch {
      setDbMsg('연결 실패'); setDbOk(false)
    }
  }

const fetchItems = async () => {
  try {
    setLoading(true)
    const res  = await fetch(`${API}/items`)
    const data = await res.json()
    setItems(Array.isArray(data) ? data : [])       // ← 방어 코드
    if (!Array.isArray(data)) setError(`API 응답 오류: ${JSON.stringify(data)}`)
  } catch (e) {
    setError(`API 오류: ${e.message}`)
  } finally {
    setLoading(false)
  }
}

  const addItem = async () => {
    await fetch(`${API}/items`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ name: newName, content: newContent })
    })
    setNewName(''); setNewContent('')
    fetchItems()
  }

  const deleteItem = async (id) => {
    await fetch(`${API}/items/${id}`, { method: 'DELETE' })
    fetchItems()
  }

  useEffect(() => { checkDB(); fetchItems() }, [])

  const statusColor = dbOk === null ? '#fef3c7' : dbOk ? '#d1fae5' : '#fee2e2'
  const statusText  = dbOk === null ? '#92400e' : dbOk ? '#065f46' : '#991b1b'

  return (
    <div style={{maxWidth:'700px',margin:'40px auto',padding:'0 20px',fontFamily:'sans-serif'}}>
      <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'24px'}}>
        <h1 style={{fontSize:'18px'}}>⚛️ React + FastAPI + Supabase</h1>
        <div style={{fontSize:'12px',padding:'4px 12px',borderRadius:'20px',background:statusColor,color:statusText}}>
          DB: {dbMsg}
        </div>
      </div>

      <div style={{display:'flex',gap:'8px',marginBottom:'20px'}}>
        <input value={newName}    onChange={e=>setNewName(e.target.value)}    placeholder="이름"
          style={{flex:1,padding:'8px 12px',border:'1px solid #d1d5db',borderRadius:'6px'}} />
        <input value={newContent} onChange={e=>setNewContent(e.target.value)} placeholder="내용"
          style={{flex:2,padding:'8px 12px',border:'1px solid #d1d5db',borderRadius:'6px'}} />
        <button onClick={addItem} disabled={!newName}
          style={{padding:'8px 16px',background:'#3b82f6',color:'white',border:'none',borderRadius:'6px',cursor:'pointer'}}>
          추가
        </button>
      </div>

      {loading && <div style={{color:'#6b7280',textAlign:'center',padding:'20px'}}>로딩 중...</div>}
      {error   && <div style={{color:'#dc2626',padding:'12px',background:'#fee2e2',borderRadius:'6px'}}>{error}</div>}
      {!loading && !error && (
        <ul style={{listStyle:'none',padding:0}}>
          {items.map(item => (
            <li key={item.id} style={{display:'flex',alignItems:'center',gap:'10px',padding:'12px',borderBottom:'1px solid #e5e7eb'}}>
              <span style={{fontFamily:'monospace',fontSize:'11px',color:'#9ca3af',width:'28px'}}>#{item.id}</span>
              <span style={{fontWeight:600,fontSize:'13px',width:'140px'}}>{item.name}</span>
              <span style={{flex:1,fontSize:'13px',color:'#6b7280'}}>{item.content}</span>
              <button onClick={()=>deleteItem(item.id)}
                style={{padding:'4px 10px',background:'#fee2e2',color:'#dc2626',border:'none',borderRadius:'4px',cursor:'pointer',fontSize:'11px'}}>
                삭제
              </button>
            </li>
          ))}
        </ul>
      )}
    </div>
  )
}

// dx-logis-playground/frontend-vue/src/App.vue
<template>
  <div class="app">
    <header>
      <div class="header-top">
        <h1>⚡ Vue + FastAPI + Supabase</h1>
        <div class="status" :class="dbStatus">DB: {{ dbMessage }}</div>
      </div>
      <nav class="manual-nav">
        <span class="nav-label">📖 매뉴얼</span>
        <a href="/render-setup-manual.html" target="_blank" class="nav-link">
          🚀 Render 환경 구성 가이드
        </a>
        <a href="/fullstack-test-manual.html" target="_blank" class="nav-link">
          🔗 Full Stack 연결 테스트 가이드
        </a>
      </nav>
    </header>

    <section class="add-form">
      <input v-model="newName"    placeholder="이름"  />
      <input v-model="newContent" placeholder="내용"  />
      <button @click="addItem" :disabled="!newName">추가</button>
    </section>

    <div v-if="loading" class="loading">로딩 중...</div>
    <div v-else-if="error" class="error">{{ error }}</div>
    <ul v-else class="list">
      <li v-for="item in items" :key="item.id">
        <span class="id">#{{ item.id }}</span>
        <span class="name">{{ item.name }}</span>
        <span class="content">{{ item.content }}</span>
        <button @click="deleteItem(item.id)">삭제</button>
      </li>
    </ul>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000'

const items      = ref([])
const loading    = ref(true)
const error      = ref(null)
const dbMessage  = ref('확인 중...')
const dbStatus   = ref('checking')
const newName    = ref('')
const newContent = ref('')

async function checkDB() {
  try {
    const res  = await fetch(`${API}/db-check`)
    const data = await res.json()
    dbMessage.value = `연결됨 (총 ${data.items_count}건)`
    dbStatus.value  = 'ok'
  } catch {
    dbMessage.value = '연결 실패'
    dbStatus.value  = 'fail'
  }
}

async function fetchItems() {
  try {
    loading.value = true
    const res  = await fetch(`${API}/items`)
    const data = await res.json()
    items.value = Array.isArray(data) ? data : []
    if (!Array.isArray(data)) error.value = `API 응답 오류: ${JSON.stringify(data)}`
  } catch (e) {
    error.value = `API 오류: ${e.message}`
  } finally {
    loading.value = false
  }
}

async function addItem() {
  await fetch(`${API}/items`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ name: newName.value, content: newContent.value })
  })
  newName.value = newContent.value = ''
  await fetchItems()
}

async function deleteItem(id) {
  await fetch(`${API}/items/${id}`, { method: 'DELETE' })
  await fetchItems()
}

onMounted(() => { checkDB(); fetchItems() })
</script>

<style scoped>
* { box-sizing: border-box; }
.app { max-width: 700px; margin: 40px auto; padding: 0 20px; font-family: sans-serif; }

/* header */
header { margin-bottom: 24px; }
.header-top {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 12px;
}
h1 { font-size: 18px; }

/* DB status badge */
.status { font-size: 12px; padding: 4px 12px; border-radius: 20px; }
.status.ok       { background: #d1fae5; color: #065f46; }
.status.fail     { background: #fee2e2; color: #991b1b; }
.status.checking { background: #fef3c7; color: #92400e; }

/* manual nav */
.manual-nav {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 10px 14px;
  background: #f8fafc;
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  flex-wrap: wrap;
}
.nav-label {
  font-size: 12px;
  font-weight: 600;
  color: #64748b;
  margin-right: 4px;
}
.nav-link {
  font-size: 12px;
  color: #3b82f6;
  text-decoration: none;
  padding: 4px 10px;
  background: #eff6ff;
  border: 1px solid #bfdbfe;
  border-radius: 6px;
  transition: all 0.15s;
}
.nav-link:hover { background: #dbeafe; color: #1d4ed8; }

/* form */
.add-form { display: flex; gap: 8px; margin-bottom: 20px; }
.add-form input {
  flex: 1;
  padding: 8px 12px;
  border: 1px solid #d1d5db;
  border-radius: 6px;
  font-size: 13px;
}
.add-form button {
  padding: 8px 16px;
  background: #3b82f6;
  color: white;
  border: none;
  border-radius: 6px;
  cursor: pointer;
}
.add-form button:disabled { opacity: 0.4; cursor: not-allowed; }

/* list */
.loading { color: #6b7280; padding: 20px; text-align: center; }
.error   { color: #dc2626; padding: 12px; background: #fee2e2; border-radius: 6px; }
.list    { list-style: none; padding: 0; }
.list li {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 12px;
  border-bottom: 1px solid #e5e7eb;
}
.id      { font-family: monospace; font-size: 11px; color: #9ca3af; width: 28px; }
.name    { font-weight: 600; font-size: 13px; width: 140px; }
.content { flex: 1; font-size: 13px; color: #6b7280; }
.list li button {
  padding: 4px 10px;
  background: #fee2e2;
  color: #dc2626;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 11px;
}
</style>
